AwakeService: 唤醒服务
  UdpSessionController: 发送唤醒信息
  ChannelMessageProcessor: 结束时广播
CacheAccessor: channel本地缓存及redis缓存的读写
CommandProcessor: 指令处理器
  CacheAccessor:
  SessionRegistry: 获取网关tcp信息
  ChannelMessageProcessor: 指令请求处理失败时批量回复
  AwakeService:
ClientMessageProcessor: 直接回复终端
SessionRegistry: 连接管理
  CacheAccessor: 网关登录后在redisServer上登记
  StateController: 超时网关被强制关闭后进行相应处理
  ChannelMessageProcessor: 网关登录成功后在tcpServer广播
  CommandProcessor: 网关登录成功后立即尝试执行任务,网关关闭连接时尝试取消所有任务



